In [2]:
import numpy as np

def avm(l, n, increasing = False):
    if increasing:
        print(np.array([ j** i for j in l for i in range(N)]).reshape(len(l), n))
    else:
        print(np.array([ j** (n-1-i) for j in l for i in range(N)]).reshape(len(l), n))
        
ml = [1,2,3]
n = 4

avm(np.array(ml),n)

avm(np.array(ml),n, increasing= True)

[[ 1  1  1  1]
 [ 8  4  2  1]
 [27  9  3  1]]
[[ 1  1  1  1]
 [ 1  2  4  8]
 [ 1  3  9 27]]


In [2]:
var= [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] 
window = 3
result = []

for i in range(len(var)):
    if i != len(var)-2:
        result.append((var[i]+var[i+1]+var[i+2])/window)
    else:
        break
resultsize = len(var)-window+1
print(resultsize)
print(len(result))
for j in range(len(result)):
    print(f'y{j+1} = {result[j]}')

11
11
y1 = 5.0
y2 = 4.666666666666667
y3 = 5.666666666666667
y4 = 6.666666666666667
y5 = 9.666666666666666
y6 = 28.666666666666668
y7 = 49.333333333333336
y8 = 72.66666666666667
y9 = 84.0
y10 = 93.33333333333333
y11 = 116.33333333333333
